// Calc.swift — Tally's expression engine, ported from the React Native
// app's src/lib/calc-engine.ts. Flat expressions only: + − × ÷, decimals,
// iOS-style percent, and reference tokens.
//
// References: an expression may embed `{e123}` (the value of another line in
// the same tab, by entry id) or `{sum}` (the running total of every line above
// it). Tokens resolve through a caller-supplied closure at evaluation time, so
// lines stay *live* — edit the referenced line and every dependent recomputes.
//
// ── On fidelity ─────────────────────────────────────────────────────────────
// This file is checked against a fixture generated by running the original
// TypeScript engine over ~2,100 expressions (Tools/gen-engine-fixture.mjs). It
// is a port, not a rewrite: where the original is quirky, so is this, because
// people have saved tabs whose numbers were produced by those quirks and a
// shared tab must read the same on the web as it does here.
//
// The quirks worth knowing about, all covered by the fixture:
//   · a '-' where a value belongs is a unary minus and stacks ("−−5" is 5);
//     any other operator in that position is dropped
//   · '%' directly after '+' or '−' is a percentage *of the previous value*
//     ("200+10%" is 220); anywhere else it is simply /100
//   · a trailing operator is dropped as an incomplete expression ("5+" is 5)
//   · two adjacent references with no operator between them evaluate to the
//     first alone — the second is parsed, then discarded with the trailing
//     operators. Unreachable through the keypad, which always joins with '+'.
//   · an unresolvable reference poisons the whole expression (nil), rather
//     than quietly resolving to zero
//   · division by zero is nil, not infinity
import Foundation

public enum Calc {

  // MARK: - Reference tokens

  // The three patterns below are computed rather than stored. `Regex` is not
  // `Sendable` — it compiles its program lazily — so a `static let` is neither
  // allowed under strict concurrency nor actually safe to share. Rebuilding a
  // pattern this small costs microseconds against expressions that are a few
  // dozen characters long, which is well below anything a keystroke would feel.

  /// One reference token, e.g. `{e103}` or `{sum}`.
  static var refPattern: Regex<(Substring, Substring)> { /\{(e\d+|sum)\}/ }

  /// All reference ids used by an expression, in order of appearance.
  public static func refs(in raw: String?) -> [String] {
    guard let raw else { return [] }
    return raw.matches(of: refPattern).map { String($0.1) }
  }

  /// An expression split into literal text runs and reference tokens.
  public enum Segment: Equatable, Sendable {
    case text(String)
    case ref(String)
  }

  /// Split an expression for display — text runs stay text, tokens become refs.
  public static func split(_ raw: String) -> [Segment] {
    var out: [Segment] = []
    var last = raw.startIndex
    let pattern = refPattern
    for m in raw.matches(of: pattern) {
      if m.range.lowerBound > last {
        out.append(.text(String(raw[last..<m.range.lowerBound])))
      }
      out.append(.ref(String(m.1)))
      last = m.range.upperBound
    }
    if last < raw.endIndex { out.append(.text(String(raw[last...]))) }
    return out
  }

  /// An expression as one flat display string, each reference token replaced by
  /// its name — "65×{e12}" reads as "65× Rate". For the places that can't draw
  /// pills, like a row's accessibility label.
  public static func text(_ raw: String, nameFor: (String) -> String) -> String {
    split(raw)
      .map { seg in
        switch seg {
        case .text(let t): return t
        case .ref(let id): return " " + nameFor(id)
        }
      }
      .joined()
      .trimmingCharacters(in: .whitespacesAndNewlines)
  }

  // MARK: - Evaluation

  /// Resolves a reference token to a number. `id` is `e123`-style or `sum`.
  public typealias RefResolver = (String) -> Double?

  private enum Op: Character { case add = "+", sub = "-", mul = "*", div = "/" }

  /// Tokens: references, numbers (optionally trailing %) and binary operators.
  /// Anything else in the string is simply not matched, and so ignored.
  private static var tokenPattern: Regex<Substring> { /\{(?:e\d+|sum)\}|\d*\.?\d+%?|[+\-*\/]/ }

  /**
   Evaluate a flat expression string (no parens). Returns a value or nil.
   Reference tokens resolve through `resolve`; an unresolvable token makes the
   whole expression invalid rather than silently wrong.
   */
  public static func evaluate(_ raw: String?, resolve: RefResolver? = nil) -> Double? {
    guard let raw else { return nil }
    let s = raw
      .trimmingCharacters(in: .whitespacesAndNewlines)
      .replacingOccurrences(of: "×", with: "*")
      .replacingOccurrences(of: "÷", with: "/")
      .replacingOccurrences(of: "−", with: "-")
    if s.isEmpty { return nil }

    var vals: [Double] = []
    var ops: [Op] = []
    // Set when a '-' appears where a value is expected (the start of the
    // expression, or right after an operator) — a unary minus applied to the
    // next value. It stacks, so "−−5" is 5.
    var neg = false

    // Compiled once for the whole scan rather than per token.
    let tokens = s.matches(of: tokenPattern)
    for m in tokens {
      let t = String(m.output)

      if let op = t.count == 1 ? Op(rawValue: t.first!) : nil {
        if vals.isEmpty || ops.count == vals.count {
          // Where a value belongs: '-' negates the value to come, anything
          // else is a stray operator and is dropped.
          if op == .sub { neg.toggle() }
          continue
        }
        ops.append(op)

      } else if t.hasPrefix("{") {
        let id = String(t.dropFirst().dropLast())
        guard let v = resolve?(id), v.isFinite else { return nil }
        vals.append(neg ? -v : v)
        neg = false

      } else {
        let pct = t.hasSuffix("%")
        // strtod, not Double(_:) — the token grammar allows a leading '.'
        // (".5"), which Swift's own initialiser rejects outright.
        var n = strtod(pct ? String(t.dropLast()) : t, nil)
        if !n.isFinite { continue }
        if pct {
          // iOS Calculator's percent: after + or −, a percentage *of the
          // running left-hand side; otherwise just a hundredth.
          if let prev = vals.last, let lastOp = ops.last, lastOp == .add || lastOp == .sub {
            n = (prev * n) / 100
          } else {
            n = n / 100
          }
        }
        vals.append(neg ? -n : n)
        neg = false
      }
    }

    if vals.isEmpty { return nil }

    // Drop trailing operators (an incomplete expression), and with them any
    // value that has no operator reaching it.
    while ops.count >= vals.count { ops.removeLast() }

    // First pass: * and /.
    var rv: [Double] = [vals[0]]
    var ro: [Op] = []
    for k in 0..<ops.count {
      let next = vals[k + 1]
      switch ops[k] {
      case .mul: rv[rv.count - 1] *= next
      case .div: rv[rv.count - 1] = next == 0 ? Double.nan : rv[rv.count - 1] / next
      case .add, .sub:
        ro.append(ops[k])
        rv.append(next)
      }
    }

    // Second pass: + and −, left to right.
    var res = rv[0]
    for k in 0..<ro.count { res = ro[k] == .add ? res + rv[k + 1] : res - rv[k + 1] }
    return res.isFinite ? res : nil
  }

  /// True when the string contains a binary operator between two values (so the
  /// row is worth showing the expression under the amount). `{` and `}` count
  /// as value edges, so `{e1}×3` reads as an operation too.
  public static func hasOperator(_ raw: String?) -> Bool {
    guard let raw else { return false }
    return raw.firstMatch(of: /[\d}]\s*[+\-*\/×÷−]\s*[\d{]/) != nil
  }

  // MARK: - Formatting

  /**
   A number as plain expression text: round-tripped through 2dp so float
   artifacts don't leak into expressions, minus rendered with the keypad's '−'.
   Used when a deleted line's references freeze into literals.

   `Math.round` in the original rounds halves toward +∞, which is `floor(x+0.5)`
   and *not* Swift's `rounded()` (halves away from zero) — they disagree on every
   negative half, so −0.125 freezes as "−0.12" here while `fmt` shows "−0.13".
   */
  public static func plain(_ n: Double) -> String {
    let r = (n * 100 + 0.5).rounded(.down) / 100
    return r < 0 ? "−" + jsString(-r) : jsString(r)
  }

  /**
   Format a number as money-ish: 2dp, thousands separators, trimmed.

   Written by hand rather than through `NumberFormatter` or `String(format:)`,
   for the same reason the original avoided `Intl`: it has to be identical
   everywhere, including in the web share page. `String(format: "%.2f")` would
   be wrong in a way that is easy to miss — C rounds halves to even, so it turns
   0.125 into "0.12", where JavaScript's `toFixed` rounds halves away from zero
   and gives "0.13". See `toFixed2`.
   */
  public static func fmt(_ n: Double?) -> String {
    guard let n, n.isFinite else { return "0.00" }
    let neg = n < 0
    let parts = toFixed2(abs(n)).split(separator: ".", maxSplits: 1)
    let whole = String(parts[0])
    let frac = parts.count > 1 ? String(parts[1]) : "00"
    return (neg ? "−" : "") + grouped(whole) + "." + frac
  }

  /// Thousands separators, from the right.
  private static func grouped(_ whole: String) -> String {
    var out = ""
    for (i, ch) in whole.reversed().enumerated() {
      if i > 0 && i % 3 == 0 { out.append(",") }
      out.append(ch)
    }
    return String(out.reversed())
  }

  /**
   JavaScript's `Number.prototype.toFixed(2)` for a non-negative, finite value:
   the integer `n` minimising |n/100 − x|, ties going to the larger `n`.

   Done on the decimal expansion rather than in floating point, because the tie
   has to be decided on the double's *exact* value: 0.125 is exactly a tie and
   rounds up, while 2.675 is really 2.67499999999999982… and rounds down.
   `%.*f` is correctly rounded, so 40 places put the decision digit far beyond
   anything that could carry into it — consecutive doubles near 1 are ~2·10⁻¹⁶
   apart, so no double sits within 10⁻⁴⁰ of a tie without being one.

   One deliberate divergence from the original, which the fixture records: at
   1e21 and above JavaScript's `toFixed` switches to exponential notation, and
   the original `fmt` then splits "1e+21" on "." and prints the string
   "1e+21.undefined". This formats the number properly instead.
   */
  private static func toFixed2(_ x: Double) -> String {
    let exact = String(format: "%.40f", x)
    let parts = exact.split(separator: ".", maxSplits: 1)
    var whole = Array(String(parts[0]))
    let frac = Array(parts.count > 1 ? String(parts[1]) : "")

    var kept = Array(frac.prefix(2))
    while kept.count < 2 { kept.append("0") }

    // Round half up: the decision digit is the third, and anything at or above
    // '5' there rounds up whether the rest is zero (an exact tie, which goes to
    // the larger n) or not.
    if frac.count > 2, let d = frac[2].wholeNumberValue, d >= 5 {
      var i = kept.count - 1
      var carry = true
      while carry && i >= 0 {
        let d = kept[i].wholeNumberValue! + 1
        carry = d == 10
        kept[i] = Character(String(carry ? 0 : d))
        i -= 1
      }
      if carry {
        var j = whole.count - 1
        while carry && j >= 0 {
          let d = whole[j].wholeNumberValue! + 1
          carry = d == 10
          whole[j] = Character(String(carry ? 0 : d))
          j -= 1
        }
        if carry { whole.insert("1", at: 0) }
      }
    }

    return String(whole) + "." + String(kept)
  }

  /**
   A number as JavaScript's `String(n)` renders it — which is not Swift's
   `"\(n)"`: Swift writes an integral double as "1000000.0", JavaScript as
   "1000000". Only `plain` needs this, and only for values already rounded to
   2dp, so the exponential forms JavaScript switches to at 1e21 and 1e-7 are far
   outside anything it will be handed.
   */
  private static func jsString(_ n: Double) -> String {
    if n == n.rounded() && abs(n) < 1e21 {
      return String(format: "%.0f", n)
    }
    var s = "\(n)"
    if s.hasSuffix(".0") { s.removeLast(2) }
    return s
  }
}
