// Draft.swift — the keypad's effect on the line being typed.
//
// Ported from the `press` and `insertRef` functions in mobile/src/app/index.tsx
// and the sizing helpers in expr-view.tsx, and checked against a fixture
// generated by running that original over every (draft, key) pair.
//
// This lives in TallyKit, away from the UI, because it is where a mistake is
// most expensive and least visible: the draft string is what the engine is
// eventually handed, so a rule that drifts produces a *valid expression that is
// the wrong one*. None of the rules are guessable from the keypad's appearance,
// and all of them are in the fixture:
//
//   · backspace deletes a whole `{e123}` pill, never its last character;
//   · an operator typed onto a trailing operator replaces it — except on an
//     empty draft, where only '−' survives, as a unary minus;
//   · '%' is ignored unless the draft ends in a digit;
//   · '.' looks at the current *term*, not the whole draft, and is ignored
//     after a pill (a pill is a finished number) or a term that already has
//     one; on an empty draft it types "0.";
//   · a digit straight after a pill starts a new term, joined with '+' — the
//     running-tab default, and the same rule the Σ insert uses in the other
//     direction.
import Foundation

/// A key on the 4×5 pad. The raw values are what the key draws where it draws a
/// character at all; the rest are SF Symbols at the call site.
public enum Key: String, CaseIterable, Sendable {
  case backspace = "⌫"
  case clear = "AC"
  case percent = "%"
  case divide = "÷"
  case seven = "7", eight = "8", nine = "9"
  case multiply = "×"
  case four = "4", five = "5", six = "6"
  case minus = "−"
  case one = "1", two = "2", three = "3"
  case plus = "+"
  case note = "✎"
  case zero = "0"
  case dot = "."
  case enter = "↵"

  /// The pad, in the order it is drawn. The top row follows the iOS
  /// Calculator's (⌫ · AC · % · ÷) so muscle memory from the system app
  /// transfers.
  public static let rows: [[Key]] = [
    [.backspace, .clear, .percent, .divide],
    [.seven, .eight, .nine, .multiply],
    [.four, .five, .six, .minus],
    [.one, .two, .three, .plus],
    [.note, .zero, .dot, .enter],
  ]

  /// Keys that are commands the screen handles, not edits to the draft: AC
  /// clears, ✎ toggles the note field, ↵ commits.
  public var isCommand: Bool { self == .clear || self == .note || self == .enter }

  var isOperator: Bool { self == .plus || self == .minus || self == .multiply || self == .divide }
}

public enum Draft {

  /// A key's effect on the draft, or nil for a key the screen handles itself.
  public static func apply(_ key: Key, to d: String) -> String? {
    switch key {
    case .clear, .note, .enter:
      return nil

    case .backspace:
      // A pill goes whole. Anything else loses its last character — including
      // a lone brace or a malformed token, which are not pills.
      if let m = d.firstMatch(of: /\{(?:e\d+|sum)\}$/) {
        return String(d[d.startIndex..<m.range.lowerBound])
      }
      return d.isEmpty ? d : String(d.dropLast())

    case .percent:
      return d.last?.isNumber == true ? d + "%" : d

    case .plus, .minus, .multiply, .divide:
      if d.isEmpty { return key == .minus ? "−" : "" }
      if isTrailingOperator(d) { return String(d.dropLast()) + key.rawValue }
      return d + key.rawValue

    case .dot:
      // The current term, not the whole draft — "1.5+2" may still take a dot.
      //
      // `omittingEmptySubsequences: false` is load-bearing, and Swift's default
      // is the opposite of JavaScript's. After a trailing operator the current
      // term is the *empty* one after it ("{e101}+" → ["{e101}", ""]), and
      // dropping that empty run would hand back the pill instead, which then
      // refuses the dot as "a finished number". The fixture catches it.
      let seg =
        d.split(omittingEmptySubsequences: false, whereSeparator: { "+-−×÷*/".contains($0) })
        .last.map(String.init) ?? ""
      if seg.hasSuffix("}") { return d }  // a pill is a finished number
      if seg.contains(".") { return d }
      return d.isEmpty ? "0." : d + "."

    default:
      // A digit straight after a pill starts a new term.
      return d.hasSuffix("}") ? d + "+" + key.rawValue : d + key.rawValue
    }
  }

  /**
   Drop a reference token into the draft.

   Mid-number, or right after another pill, a running tab adds things — so
   joining with '+' is the predictable default, and the preview shows exactly
   what happened.
   */
  public static func insertRef(_ id: String, into d: String) -> String {
    let token = "{\(id)}"
    if d.isEmpty { return token }
    if isTrailingOperator(d) { return d + token }
    return d + "+" + token
  }

  private static func isTrailingOperator(_ d: String) -> Bool {
    guard let last = d.last else { return false }
    return "+-−×÷*/".contains(last)
  }

  // MARK: - Sizing

  public static let fontSize: CGFloat = 36

  /**
   Rendered width of a draft, in characters.

   Reference tokens count as the name actually drawn in the pill, not as their
   `{e123}` source — otherwise a draft holding one short pill would be treated
   as long and shrink for no reason.
   */
  public static func length(_ expr: String, nameFor: (String) -> String) -> Int {
    Calc.split(expr).reduce(0) { n, seg in
      switch seg {
      case .text(let t): return n + t.count
      case .ref(let id): return n + nameFor(id).count + 1
      }
    }
  }

  /**
   One step down once the line is long enough to crowd the card, mirroring the
   design's 40 → 30.

   Past that the line stops shrinking and starts running off the leading edge
   (see DraftLine): shrinking all the way to fit would make a long sum
   unreadable, and the head of it matters far less than the digits still being
   typed.
   */
  public static func fontSize(forLength len: Int) -> CGFloat { len > 11 ? 27 : fontSize }
}
