// Pipeline.swift — the live-reference pipeline, ported from the pass that every
// write to the running list goes through in the React Native store.
//
// Entries can reference each other (`{e123}`) or the running subtotal
// (`{sum}`). Every write funnels through `pipeline(from:to:)` so the invariants
// hold no matter which screen made the change:
//
//   1. every line has a sticky number (backfilled for pre-reference data);
//   2. references to lines that just vanished freeze into their last value;
//   3. every referencing line's value is recomputed in one forward pass — the
//      picker only ever offers lines *above* the one being written, so list
//      order is evaluation order and cycles cannot exist by construction.
//
// Checked against a fixture generated by running the original TypeScript over
// 422 scenarios (Tools/gen-pipeline-fixture.mjs).
import Foundation

/// Sticky line numbers: assigned once, never reshuffled. Deleting line 2 leaves
/// a gap rather than renaming every reference that pointed past it.
public func assignNums(_ list: [Entry]) -> [Entry] {
  var next = (list.compactMap(\.num).max() ?? 0) + 1
  return list.map { e in
    guard e.num == nil else { return e }
    var out = e
    out.num = next
    next += 1
    return out
  }
}

/**
 Replace references to removed lines with their last known value.

 A removed line that was itself in error has no value worth keeping, so its
 token is left in place and the dependent goes into error rather than quietly
 becoming zero.
 */
public func freezeRefs(from prev: [Entry], to list: [Entry]) -> [Entry] {
  let kept = Set(list.map(\.id))
  var removed: [String: Double] = [:]
  for e in prev where !kept.contains(e.id) && e.error != true { removed[e.id] = e.value }
  if removed.isEmpty { return list }

  return list.map { e in
    if e.expr.isEmpty { return e }

    var rebuilt = ""
    var last = e.expr.startIndex
    for m in e.expr.matches(of: Calc.refPattern) {
      rebuilt += e.expr[last..<m.range.lowerBound]
      let id = String(m.1)
      rebuilt += removed[id].map(Calc.plain) ?? String(m.0)
      last = m.range.upperBound
    }
    rebuilt += e.expr[last...]
    if rebuilt == e.expr { return e }

    var out = e
    // A pure reference may have frozen into a bare number, which is no longer
    // worth showing as an expression under the amount.
    let keepExpr = Calc.hasOperator(rebuilt) || !Calc.refs(in: rebuilt).isEmpty
    out.expr = keepExpr ? rebuilt : ""
    return out
  }
}

/**
 Recompute referencing lines top to bottom; plain lines keep their value.

 A line that can't be evaluated is marked `error` and carries 0 — and stays out
 of the resolved table, so anything referencing it errors too rather than
 reading a number that means nothing. `{sum}` is the counted lines above it,
 where a line already in error contributes zero rather than poisoning the sum.
 */
public func recalc(_ list: [Entry]) -> [Entry] {
  var resolved: [String: Double] = [:]  // errored lines are deliberately absent
  var out: [Entry] = []
  out.reserveCapacity(list.count)

  for (i, e) in list.enumerated() {
    var v = e.value
    var err = false

    if !e.expr.isEmpty && !Calc.refs(in: e.expr).isEmpty {
      let r = Calc.evaluate(e.expr) { id in
        if id == "sum" {
          var sum = 0.0
          for k in 0..<i where list[k].isCounted { sum += resolved[list[k].id] ?? 0 }
          return sum
        }
        // Only lines above have resolved — a forward reference (impossible
        // through the UI) or an errored line resolves to nothing.
        return resolved[id]
      }
      if let r { v = r } else {
        err = true
        v = 0
      }
    }

    if !err { resolved[e.id] = v }
    var next = e
    next.value = v
    next.error = err ? true : nil
    out.append(next)
  }
  return out
}

/// The whole pass, in the order the invariants depend on.
public func pipeline(from prev: [Entry], to next: [Entry]) -> [Entry] {
  recalc(freezeRefs(from: prev, to: assignNums(next)))
}
